config/routes.rb
ClistApp::Application.routes.draw do
  resources :instruments

  devise_for :users
  resources :users, :only => [:show]

get 'about' => 'pages#about'

root :to => 'pages#home'

match 'user/:id' => 'users#show'

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  attr_accessible :description, :image, :name, :type

  validates :description, presence: true
  validates :name, presence: true
  validates :type, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  						content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  						size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instruments }
    end
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
    @instrument = Instrument.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instrument }
    end
  end

  # GET /instruments/new
  # GET /instruments/new.json
  def new
    @instrument = current_user.instruments.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instrument }
    end
  end

  # GET /instruments/1/edit
  def edit
    @instrument = current_user.instruments.find(params[:id])
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = current_user.instruments.new(params[:instrument])

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render json: @instrument, status: :created, location: @instrument }
      else
        format.html { render action: "new" }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instruments/1
  # PUT /instruments/1.json
  def update
    @instrument = current_user.instruments.find(params[:id])

    respond_to do |format|
      if @instrument.update_attributes(params[:instrument])
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument = current_user.instruments.find(params[:id])
    @instrument.destroy

    respond_to do |format|
      format.html { redirect_to instruments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def show
	@user = User.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/instruments/_form.html.erb
<%= simple_form_for(@instrument, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an image" %>
  <%= f.input :name, label: "What is your instrument's name?" %>
  <%= f.input :type, label: "What kind of instrument is it?", :collection => ["piano","saxaphone","trumpet"] %>
  <%= f.input :description, as: :text, input_html: { rows: "3"} %>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/instruments/_instrument.html.erb
<div class="box">
	<%= link_to (image_tag instrument.image), instrument %>
	<p class="description">
		<%= instrument.description %>
	</p>
	<p>
		<strong>
			Posted by <%= instrument.user.name %>
		</strong>
	</p>
	  
	<% if current_user == instrument.user %>
		<p>
		<%= link_to 'Edit', edit_instrument_path(instrument) %>
		<%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>
</div>








<!-- Temporary moved down to try out jquery masonry
<tr>
  <td><%#= image_tag instrument.image %></td>
  <td><%#= instrument.description %></td>
  <td><%#= link_to 'Show', instrument %></td>
  
  <%# if current_user == instrument.user %>
	  <td><%#= link_to 'Edit', edit_instrument_path(instrument) %></td>
	  <td><%#= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <%# end %>
</tr>
-->

app/views/instruments/edit.html.erb
<h1>Editing instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<div id="instruments">
  <%= render @instruments %>
</div>











<!--
 Temporary moved down to try out jquery masonry

<h1>Listing instruments</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <%#= render @instruments %>   
  </tbody>
</table>

<br />

<%#= link_to 'New Instrument', new_instrument_path %>
-->

app/views/instruments/new.html.erb
<h1>New instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @instrument.image %>
		<p>
		  <%= @instrument.description %>
		</p>
		<p>
		  <%= @instrument.user.name %>
		</p>
		<% if current_user == @instrument.user %>
			<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
		<% end %>
		<%= link_to 'Back', instruments_path %>
	</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "Beta:Full Site Coming Soon!", "http://andante.cc" %> Created by the Andante Team - San Francisco, CA
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "A Company", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	      	<li><%= link_to "About Us", about_path %></li>
          <li><%= link_to "Instruments", instruments_path %></li>
      </ul>
      <ul class="nav pull-right">
        <% if user_signed_in? %>
          <li><%= link_to "Add +", new_instrument_path %></li>
            <li><%= link_to current_user.name, user_path(current_user) %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>'A Company'</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<%flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
				<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>

	</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %> 
	is a project to teach 
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %> 
	in one month. This is a sample application.
</p> 

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<h1>Welcome to Andante!</h1>
	<p>Welcome to the home page of the soon to be best place to rent, and lend musical instruments! <br/> We here at Andante Love making and listening to music and are glad we could join you on your adventure. </p>
<% else %>
<div class="hero-unit">
	<h1>Welcome to "A Company's Webpage"!</h1>
	<p>
		You've found the the soon to be Andante home page. This website is under construction. Go to  
		<%= link_to "our coming soon page", "http://andante.cc" %> 
			to recieve updates about Andante.
	</p>
		<span>
			<div class="row-fluid">
				<div class="span6">
				Give it a Try!!!
				</div>
				<div class="span6">
				Already a user?
				</div>
			</div>
		</span>
		<span>
			<div class="row-fluid">
				<div class="span6">
				<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
				</div>
				<div class="span6">
				<%= link_to "Login   ", new_user_session_path, class: "btn btn-primary btn-large" %>
				</div>
			</div>
		</span>
</div>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>